chore: remove unused imports (#497)
For some reason the Typescript/ESLint config in this repo doesn't detect
these unused imports.

The only reason I discovered them, was that when I tried to run the main
CLI repo's tests, I still had the local plugin-functions yarn linked in, so it
run those against this repository instead, which resulted in:

```
$ ./bin/dev snapshot:compare
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/lib/log-stream-utils.ts:42:61 - error TS2304: Cannot find name 'EventSourceOptions'.

42 function eventSourceStream(url: string, eventSourceOptions: EventSourceOptions, tail?: boolean): Stream.Readable {
                                                               ~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/generate/function.ts:9:1 - error TS6133: 'cli' is declared but its value is never read.

9 import { cli } from 'cli-ux';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/run/function.ts:15:1 - error TS6133: 'FunctionsFlagBuilder' is declared but its value is never read.

15 import { FunctionsFlagBuilder } from '../../lib/flags';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/whoami/functions.ts:8:1 - error TS6133: 'cli' is declared but its value is never read.

8 import { cli } from 'cli-ux';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../plugin-functions/src/commands/whoami/functions.ts:11:1 - error TS6133: 'FunctionsFlagBuilder' is declared but its value is never read.

11 import { FunctionsFlagBuilder } from '../../lib/flags';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/lib/log-stream-utils.ts:42:61 - error TS2304: Cannot find name 'EventSourceOptions'.

42 function eventSourceStream(url: string, eventSourceOptions: EventSourceOptions, tail?: boolean): Stream.Readable {
                                                               ~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/env/var/get.ts:11:1 - error TS6133: 'cli' is declared but its value is never read.

11 import { cli } from 'cli-ux';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/login/functions/jwt.ts:22:11 - error TS6196: 'OAuthToken' is declared but never used.

22 interface OAuthToken {
             ~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/run/function/start.ts:11:1 - error TS6133: 'cli' is declared but its value is never read.

11 import { cli } from 'cli-ux';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

module: @oclif/core@1.16.0
task: toCached
plugin: @salesforce/plugin-functions
root: /Users/emorley/src/plugin-functions
See more details with DEBUG=*
(node:3457) TSError Plugin: @salesforce/plugin-functions: ⨯ Unable to compile TypeScript:
../plugin-functions/src/commands/env/compute/collaborator/add.ts:9:18 - error TS6133: 'Flags' is declared but its value is never read.

9 import { Errors, Flags } from '@oclif/core';
                   ~~~~~
```

GUS-W-11763062.